### ISSUE TITLE
building lower versions of jax gives "Problem getting python include path."

### ISSUE THREAD

**Issue by DeXtmL** [cloudhan/jax-windows-builder#10]
I am trying to build jaxlib 0.1.64 which is required by Jax 0.2.12 for GPT-J
It cannot build. The detailed error messages are:
`ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "C:/users/runneradmin/bzl_out/ktt4c75d/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 41, in _create_local_python_repository
		python_include = _get_python_include(repository_ctx, python_bin)
	File "C:/users/runneradmin/bzl_out/ktt4c75d/external/org_tensorflow/third_party/py/python_configure.bzl", line 152, column 21, in _get_python_include
		result = execute(
	File "C:/users/runneradmin/bzl_out/ktt4c75d/external/org_tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
		fail(  
Error in fail: Problem getting python include path.`

Any idea?

**Comment by cloudhan** [comment]
It is not possible to build jaxlib older than some specific version, the first windows build starts with 0.1.58, but some 0.1.6x versions have error, not sure it is related with that or not.

**Comment by DeXtmL** [comment]
I dont think it cannot be compiled yet. All the errors are about bazel paths, it not even have started the compilation. Unfortunately I know nothing about bazel, maybe shed some light here if you got some ideas. This can be a good patch for this repo.

**Comment by DeXtmL** [comment]
Check my fork repo for detailed build steps for JAX 0.2.21 and jaxlib 0.1.62-0.1.68 for anyone who's interested.
This issue is now closed
