### ISSUE TITLE
Seems to install okay but python says jaxlib is not installed after

### ISSUE THREAD

**Issue by erispe** [cloudhan/jax-windows-builder#21]
I've tried a few different cuda WHL's of Jax, and pip says it successfully installs them. But when I try to run a script using the pipeline module it fails saying jaxlib is not installed. Is jaxlib a seperate module? If I try to pip install jaxlib it just tries to install jax (which fails, which is why I am using the jax-windows-builder whl link using this command:
`pip install jax[cuda111] -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver`

Console output from virtual environment
```
(virtual_env) D:\Projects\python_virtv\virtual_env\Scripts>pip install jax[cuda111] -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver
Looking in links: https://whls.blob.core.windows.net/unstable/index.html
Processing c:\users\erispe\appdata\local\pip\cache\wheels\4a\ca\ed\ae451e0a70bc64df2bc46d2253c210302b7b517aeeb72e4755\jax-0.4.1-py3-none-any.whl
  WARNING: jax 0.4.1 does not provide the extra 'cuda111'
Requirement already satisfied: opt-einsum in d:\projects\python_virtv\virtual_env\lib\site-packages (from jax[cuda111]) (3.3.0)
Requirement already satisfied: numpy>=1.20 in d:\projects\python_virtv\virtual_env\lib\site-packages (from jax[cuda111]) (1.24.1)
Requirement already satisfied: scipy>=1.5 in d:\projects\python_virtv\virtual_env\lib\site-packages (from jax[cuda111]) (1.10.0)
Installing collected packages: jax
Successfully installed jax-0.4.1
```

Then when I run the script using a pipeline model, in this case gpt-jp, I get this
```
(virtual_env) D:\Projects\python_virtv\virtual_env\Scripts>python ../gtpjp_quickstart.py
Traceback (most recent call last):
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\jax\_src\lib\__init__.py", line 25, in <module>
    import jaxlib as jaxlib
ModuleNotFoundError: No module named 'jaxlib'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\python_virtv\virtual_env\gtpjp_quickstart.py", line 2, in <module>
    from transformers import pipeline
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\transformers\utils\generic.py", line 36, in <module>
    import jax.numpy as jnp
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\jax\__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\jax\config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\jax\_src\config.py", line 28, in <module>
    from jax._src import lib
  File "D:\Projects\python_virtv\virtual_env\lib\site-packages\jax\_src\lib\__init__.py", line 27, in <module>
    raise ModuleNotFoundError(
ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.
```

**Comment by erispe** [comment]
Nevermind, seems like jaxlib is a separate module and can be installed using this. So I will try it later
https://gist.github.com/nitish1295/48c693a702efb9b165f18aa65f43e235
